### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by jackwzp** [LittoCats/react-native-path#1]
Hi,

Can you explain how to use this? I'm looking for something that would help me with relative import path in my React Native app.

```
import SomeStuff from '../../../myStuff'
```
to

```
import SomeStuff from 'myStuff'
```

Is this possible with this library?

**Comment by LittoCats** [comment]
Apologize for poor explanation.

Now, I have published this repository on [npm](www.npmjs.com).

And commit [README](https://github.com/LittoCats/react-native-path/blob/master/README.md).
